#!/usr/bin/env bash

bsp_workspace_yuck() {
    desktops=$(bspc query -D --names)
    focused_desktops=$(bspc query -D -d focused --names)
    occupied_desktops=$(bspc query -D -d .occupied --names)
    urgent_desktops="$(bspc query -D -d .urgent --names)"

    buffered=""
    for d in $desktops; do

      # focus
      if echo $focused_desktops | grep -q $d; then
          active_class="active"
      else
          active_class="inactive"
      fi

      # occupied / urgent
      if echo $occupied_desktops| grep -q $d; then
          button_class="occupied"
      elif echo $urgent_desktops | grep -q $d; then
          button_class="urgent"
      else
          button_class="empty"
      fi

      button_name=$d
      buffered+="(button :class \"$button_class $active_class\"  :onclick \"bspc desktop -f $d\" \"$button_name\")"
  done

  echo "(box :orientation \"v\" :class \"workspaces\" :halign \"center\" :valign \"center\" :vexpand true :hexpand true $buffered)"
}

bsp_workspace_yuck
bspc subscribe desktop node_transfer | while read -r _ ; do
bsp_workspace_yuck
done
