alias s='sudo '
alias p='sudo pacman'
alias e='$EDITOR'
alias ef='$EDITOR $(fzf)'
alias grep='grep --color=auto'
alias diff='diff --color=auto'

# alias ls='ls -hN --color=auto --group-directories-first'
alias ls='exa --group-directories-first'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'

alias ..='cd ..'
alias ...='cd ../..'
alias mkd='mkdir -pv'
alias cp='cp -rv'
alias rm='rm --verbose'
alias rmf='rm -rf'

alias ende='trans en:de'
alias deen='trans de:en'

alias -g C='| mycopy'
alias -g V='| vi -'
alias -g L='| less'
alias -g M='| more'
alias -g S='| sort'

alias vcf='e ~/.config/nvim/init.vim'
alias zcf='e ~/.zshrc ~/.config/zsh/*.zsh'
alias xcf='e ~/.xinitrc ~/.Xresources'
alias bcf='e ~/.config/bspwm/bspwmrc'
alias scf='e ~/.config/sxhkd/sxhkdrc'
alias pcf='e ~/.config/polybar/config'
alias acf='e ~/.config/alacritty/alacritty.yml'
alias sqcf='e ~/.config/squash/themes/*'
