#!/bin/bash

# DEFINE COLORS
BG="#12171b"
FG="#c5c8c6"

WHT="#c4d0d8"
RED="#cc6666"
GRN="#b5bd68"
YLW="#f0c674"
BLU="#81a2be"
MAG="#b294bb"
CYN="#8abeb7"
# BLK="#26292c"
BLK="#222b33"

BWHT="#f5f8f6"
BRED="#cc6666"
BGRN="#b5bd68"
BYLW="#f0c674"
BBLU="#81a2be"
BMAG="#b294bb"
BCYN="#8abeb7"
BBLK="#5e7a8e"

# ROFI OPTIONS
ACC="${RED}"

# BAR OPTIONS
BAR_SCRIPT="infobar2"

# VIM COLORSCHEME
VIM_SCHEME='term'

# WALLPAPER OPTIONS
WALLPAPER_PATH="$HOME/Media/walls/anna/DSC_9033-white.jpg"
WALLPAPER_STYLE="fill"

# 2BWM OPTIONS
TWOBWM_FOCUS="${BYLW}"
TWOBWM_UNFOCUS="${BGRN}"
TWOBWM_FIXED="${RED}"
TWOBWM_UNKILL="${CYN}"
TWOBWM_FIXEDUNK="${MAG}"
TWOBWM_OUTR="${BG}"
TWOBWM_EMP="${BG}"

# LEMONBAR OPTIONS
LMNBAR_DARK="${BYLW}"
LMNBAR_DARKER="${BGRN}"

SQUASH_FONT=xft:Iosevka\ Nerd\ Font:size=13
SQUASH_FONT="xft:Iosevka Nerd Font:weight=medium:size=13"
# SQUASH_FONT="xft:Roboto Mono:weight=regular:size=13"
# SQUASH_FONT="xft:Fantasque Sans Mono:weight=medium:size=13"
ST_FONT="Iosevka Nerd Font:size=13"
