#!/usr/bin/env bash

# Take screenshot and display the current state as a notification

help="Usage: $(basename $0) [region]"
notification_icon=camera-photo-symbolic.symbolic
notification_miliseconds=6000
notification_id=12

directory=$HOME/Media/Screenshots/
mkdir -p $directory

if [[ "$#" -ne 1 ]]; then
    shot_path="$directory/$(date +'%Y%m%d_%H%M_grim.png')"
    grim "$shot_path"
elif [[ $1 == "region" ]]; then
    shot_path="$directory/$(date +'%Y%m%d_%H%M_grim_region.png')"
    grim -g "$(slurp)" "$shot_path"
else
    echo "$help" >&2
    exit 1
fi

ACTION=$(dunstify \
    -a "grim" "Screenshot ..." \
    -A "open_action,Open" \
    -u low \
    -t "$notification_miliseconds" \
    -i "$notification_icon" \
    -r "$notification_id")

case "$ACTION" in
  'open_action')
    # mouse3 click
    xdg-open $shot_path
    ;;
  '1')
    # nothing
    cat $shot_path | wl-copy
    dunstify "Screenshot" "Copied to clipboard" \
      -t "$notification_miliseconds" \
      -i "$notification_icon" 
    ;;
  '2')
    # mouse1 click
    url=$(curl -F'file=@'$shot_path https://0x0.st)
    echo $url | wl-copy
    dunstify "Screenhot uploaded" $url \
      -t "$notification_miliseconds" \
      -i "$notification_icon" 
    ;;
esac

