#! /bin/sh

source ~/.profile
source ~/.cache/wal/colors.sh

hide() {
    pkill -f hideIt.sh
    sleep 1.5
    hideIt.sh --name '^Polybar tray window$' --region 0x2145+10+-50 & >> /dev/null
    hideIt.sh -w --name '^polybar-main_DP-0' --direction top --signal --peek 3 & >> /dev/null
}

# desktops
if [ $HOSTNAME == "toaster" ]; then
    bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9 0
    bspc monitor DP-4 -d a s d f g
    $HOME/.config/polybar/launch.sh
else
    bspc monitor HDMI2 -d 1 2 3 4 5 6 7 8 9 0
    bspc monitor eDP1  -d a s d f g
    $HOME/.config/polybar/launch.sh laptop laptopExt
fi

# wrappers
c() { bspc config "$@";  }
R() { bspc rule -a "$@"; }
s() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

# ignore annoying defaults
# c ignore_ewmh_fullscreen enter
# c ignore_ewmh_fullscreen all
# c ignore_ewmh_focus true

c remove_disabled_monitors true
c remove_unplugged_monitors true

# padding
c top_padding    0
c bottom_padding 0
c right_padding  0
c left_padding   0

# gaps
c window_gap     20
c single_monocle true

# borders
c borderless_monocle    true
c border_width          2
c focused_border_color  $color7
c normal_border_color   $color0
c active_border_color   $color0
c presel_feedback_color $color2

# mouse
c click_to_focus        true
c focus_follows_pointer false

# rules
R qutebrowser desktop=^1
R firefox     desktop=^1

R discord desktop=^7 follow=off focus=off
R Spotify desktop=^8

R Zathura        state=tiled
R Pinentry       state=floating
R Emacs          state=tiled
R Signal         state=tiled
R Emacs|Question state=floating
R "gaime_server (DEBUG)" hidden=on

R zoom desktop=^5  state=tiled
R DDNet desktop=^9  follow=on state=fullscreen
# R DDNet desktop=^15 follow=on state=fullscreen

c external_rules_command "$HOME/.config/bspwm/external_rules" # Spotify

# programs
wmname LG3D # java
s sxhkd

# vim: set ft=sh :
