#! /bin/sh

xrdb $HOME/.Xresources
source $HOME/.cache/squash/colors
sxhkd &

padding=7
padding_bar=$((35+$padding))

bspc config window_gap				3
bspc config border_width			2
bspc config top_padding				$padding_bar
bspc config bottom_padding			$padding
bspc config right_padding			$padding
bspc config left_padding			$padding

bspc config split_ratio				0.5
bspc config click_to_focus			true
bspc config focus_follows_pointer	false
bspc config borderless_monocle		true

bspc config focused_border_color	$BWHT
bspc config normal_border_color		$BBLK
bspc config active_border_color		$WHT
bspc config presel_feedback_color	$YLW

if [ $HOSTNAME == "olo" ]; then
	# bspc monitor DP-2 -d q w e r t
	bspc monitor DP-2 -d q w e r ﭞ
	bspc monitor DP-4 -d y u i o p
	$HOME/.config/polybar/launch.sh left right
else
	bspc monitor -d q w e r t z u i o p
	$HOME/.config/polybar/launch.sh laptop
fi

bspc rule -a qutebrowser			desktop=^1
bspc rule -a code-oss				desktop=^2 follow=off
bspc rule -a "Gimp-2.10"			desktop=^4 follow=off
bspc rule -a DDNet					desktop=^5 follow=off
bspc rule -a discord				desktop=^7 follow=off
bspc rule -a ts3client_linux_amd64	desktop=^7
bspc rule -a Zathura				state=tiled
bspc rule -a Pinentry				state=floating
bspc rule -a Spotify				desktop=^8
bspc rule -a ':cv2 -*'				state=tiled
# bspc rule -a TelegramDesktop		desktop=^9 state=pseudo_tiled


bspc config external_rules_command "$HOME/.config/bspwm/external_rules" # Spotify

# vim: set ft=sh :
