#! /bin/sh

source ~/.cache/wal/colors.sh
# export bg_alpha="#22${background/'#'}"

# desktops
if [ $HOSTNAME == "olo" ]; then
	bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9 0
	bspc monitor DP-4 -d a s d f g
	$HOME/.config/polybar/launch.sh main rightM
else
	bspc monitor -d q w e r t z u i o p
	$HOME/.config/polybar/launch.sh laptop
fi

# wrappers
c() { bspc config "$@";  }
R() { bspc rule -a "$@"; }
s() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

# ignore annoying defaults
# c ignore_ewmh_fullscreen enter
# c ignore_ewmh_fullscreen all
# c ignore_ewmh_focus true

# padding
c top_padding    68
c bottom_padding 3
c right_padding  3
c left_padding   3

# gaps
c window_gap     -3
c single_monocle true

# borders
c borderless_monocle    true
c border_width          3
c focused_border_color  $color7
c normal_border_color   $color0
c active_border_color   $color8
c presel_feedback_color $color2

# mouse
c click_to_focus        true
c focus_follows_pointer false

# rules
R qutebrowser desktop=^1
R firefox     desktop=^1

R discord desktop=^7 follow=off
R Spotify desktop=^8

R Zathura        state=tiled
R Pinentry       state=floating
R Emacs          state=tiled
R Emacs|Question state=floating

R DDNet monitor=^2  follow=on state=fullscreen
# R DDNet desktop=^15 follow=on state=fullscreen

c external_rules_command "$HOME/.config/bspwm/external_rules" # Spotify

# programs
wmname LG3D # java
s sxhkd

# vim: set ft=sh :
