#!/bin/sh
#
# bspwm: external_rules_command

id=${1?};
instance=$3;
class=$2;

# window_title="$(xwininfo -id "$window_id" | sed ' /^xwininfo/!d ; s,.*"\(.*\)".*,\1,')"
window_title="$(xprop WM_NAME -id "$id" | cut -d\" -f2)"

# desktop
case $class in
	(Spotify) echo desktop=^8;;
	(TelegramDesktop) echo desktop=^9;;
	('')
		case $(ps -p "$(xdo pid $id)" -o comm= 2>/dev/null) in
			(spotify) echo desktop=^8;;
		esac;;
esac;

# state
case "$window_title" in
	'Question')
		echo "state=floating"
		echo "center=on"
		;;
esac



# vim: set ft=sh :
